In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
import pickle

In [46]:
## Load the dataset
data=pd.read_csv("Churn_Modelling.csv")
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [47]:
column_to_predict=data['Exited']

In [48]:
## Preprocess the data
### Drop irrelevant columns
data=data.drop(['RowNumber','CustomerId','Surname'],axis=1)
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [49]:
## Encode categorical variables
label_encoder_gender=LabelEncoder()
data['Gender']=label_encoder_gender.fit_transform(data['Gender'])
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [50]:
## Onehot encode 'Geography
from sklearn.preprocessing import OneHotEncoder
onehot_encoder_geo=OneHotEncoder()
geo_encoder=onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoder

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]], shape=(10000, 3))

In [51]:
onehot_encoder_geo.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [52]:
geo_encoded_df=pd.DataFrame(geo_encoder,columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [53]:
## Combine one hot encoder columns with the original data
data=pd.concat([data.drop('Geography',axis=1),geo_encoded_df],axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [54]:
data_copy=data.copy()

In [55]:
## Save the encoders and sscaler
with open('label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)

with open('onehot_encoder_geo.pkl','wb') as file:
    pickle.dump(onehot_encoder_geo,file)

In [56]:
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [57]:
scaler=StandardScaler()
data=scaler.fit_transform(data)

In [58]:
data=pd.DataFrame(data)

In [59]:
data

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,-0.326221,-1.095988,0.293517,-1.041760,-1.225848,-0.911583,0.646092,0.970243,0.021886,1.977165,0.997204,-0.578736,-0.573809
1,-0.440036,-1.095988,0.198164,-1.387538,0.117350,-0.911583,-1.547768,0.970243,0.216534,-0.505775,-1.002804,-0.578736,1.742740
2,-1.536794,-1.095988,0.293517,1.032908,1.333053,2.527057,0.646092,-1.030670,0.240687,1.977165,0.997204,-0.578736,-0.573809
3,0.501521,-1.095988,0.007457,-1.387538,-1.225848,0.807737,-1.547768,-1.030670,-0.108918,-0.505775,0.997204,-0.578736,-0.573809
4,2.063884,-1.095988,0.388871,-1.041760,0.785728,-0.911583,0.646092,0.970243,-0.365276,-0.505775,-1.002804,-0.578736,1.742740
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,1.246488,0.912419,0.007457,-0.004426,-1.225848,0.807737,0.646092,-1.030670,-0.066419,-0.505775,0.997204,-0.578736,-0.573809
9996,-1.391939,0.912419,-0.373958,1.724464,-0.306379,-0.911583,0.646092,0.970243,0.027988,-0.505775,0.997204,-0.578736,-0.573809
9997,0.604988,-1.095988,-0.278604,0.687130,-1.225848,-0.911583,-1.547768,0.970243,-1.008643,1.977165,0.997204,-0.578736,-0.573809
9998,1.256835,0.912419,0.293517,-0.695982,-0.022608,0.807737,0.646092,-1.030670,-0.125231,1.977165,-1.002804,1.727904,-0.573809
9999,1.463771,-1.095988,-1.041433,-0.350204,0.859965,-0.911583,0.646092,-1.030670,-1.076370,-0.505775,0.997204,-0.578736,-0.573809

In [60]:
data.columns=data_copy.columns

In [61]:
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,-0.326221,-1.095988,0.293517,-1.041760,-1.225848,-0.911583,0.646092,0.970243,0.021886,1.977165,0.997204,-0.578736,-0.573809
1,-0.440036,-1.095988,0.198164,-1.387538,0.117350,-0.911583,-1.547768,0.970243,0.216534,-0.505775,-1.002804,-0.578736,1.742740
2,-1.536794,-1.095988,0.293517,1.032908,1.333053,2.527057,0.646092,-1.030670,0.240687,1.977165,0.997204,-0.578736,-0.573809
3,0.501521,-1.095988,0.007457,-1.387538,-1.225848,0.807737,-1.547768,-1.030670,-0.108918,-0.505775,0.997204,-0.578736,-0.573809
4,2.063884,-1.095988,0.388871,-1.041760,0.785728,-0.911583,0.646092,0.970243,-0.365276,-0.505775,-1.002804,-0.578736,1.742740
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,1.246488,0.912419,0.007457,-0.004426,-1.225848,0.807737,0.646092,-1.030670,-0.066419,-0.505775,0.997204,-0.578736,-0.573809
9996,-1.391939,0.912419,-0.373958,1.724464,-0.306379,-0.911583,0.646092,0.970243,0.027988,-0.505775,0.997204,-0.578736,-0.573809
9997,0.604988,-1.095988,-0.278604,0.687130,-1.225848,-0.911583,-1.547768,0.970243,-1.008643,1.977165,0.997204,-0.578736,-0.573809
9998,1.256835,0.912419,0.293517,-0.695982,-0.022608,0.807737,0.646092,-1.030670,-0.125231,1.977165,-1.002804,1.727904,-0.573809
9999,1.463771,-1.095988,-1.041433,-0.350204,0.859965,-0.911583,0.646092,-1.030670,-1.076370,-0.505775,0.997204,-0.578736,-0.573809

In [62]:
## DiVide the dataset into indepent and dependent features
X=data
y=column_to_predict

## Split the data in training and tetsing sets
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [63]:
X_train

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
9254,0.367013,0.912419,-0.660018,0.341352,-1.225848,0.807737,0.646092,0.970243,1.373784,-0.505775,0.997204,-0.578736,-0.573809
1561,-0.191713,0.912419,0.293517,-0.350204,0.691389,0.807737,0.646092,0.970243,1.667407,-0.505775,-1.002804,1.727904,-0.573809
1670,-0.947028,0.912419,-1.422847,-0.695982,0.613102,-0.911583,0.646092,-1.030670,-0.246910,1.977165,-1.002804,-0.578736,1.742740
6087,-0.926334,-1.095988,-1.136786,1.378686,0.948021,-0.911583,0.646092,-1.030670,0.921446,1.977165,0.997204,-0.578736,-0.573809
6669,-1.381593,0.912419,1.628468,1.378686,1.052363,-0.911583,-1.547768,-1.030670,-1.053812,1.977165,0.997204,-0.578736,-0.573809
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5734,1.215448,0.912419,1.437761,1.032908,-0.108554,-0.911583,0.646092,0.970243,-0.534002,-0.505775,0.997204,-0.578736,-0.573809
5191,0.325625,-1.095988,1.819175,-1.387538,-1.225848,-0.911583,0.646092,0.970243,-1.728184,-0.505775,0.997204,-0.578736,-0.573809
5390,0.874005,-1.095988,-0.087897,-1.387538,-1.225848,2.527057,-1.547768,-1.030670,-0.136854,1.977165,0.997204,-0.578736,-0.573809
860,0.170424,0.912419,0.388871,1.032908,1.822949,-0.911583,0.646092,-1.030670,-0.044902,1.977165,0.997204,-0.578736,-0.573809
7270,0.480827,0.912419,1.151700,-1.387538,1.144727,-0.911583,0.646092,0.970243,-0.808747,-0.505775,-1.002804,1.727904,-0.573809

In [64]:
with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

In [65]:
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,-0.326221,-1.095988,0.293517,-1.041760,-1.225848,-0.911583,0.646092,0.970243,0.021886,1.977165,0.997204,-0.578736,-0.573809
1,-0.440036,-1.095988,0.198164,-1.387538,0.117350,-0.911583,-1.547768,0.970243,0.216534,-0.505775,-1.002804,-0.578736,1.742740
2,-1.536794,-1.095988,0.293517,1.032908,1.333053,2.527057,0.646092,-1.030670,0.240687,1.977165,0.997204,-0.578736,-0.573809
3,0.501521,-1.095988,0.007457,-1.387538,-1.225848,0.807737,-1.547768,-1.030670,-0.108918,-0.505775,0.997204,-0.578736,-0.573809
4,2.063884,-1.095988,0.388871,-1.041760,0.785728,-0.911583,0.646092,0.970243,-0.365276,-0.505775,-1.002804,-0.578736,1.742740
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,1.246488,0.912419,0.007457,-0.004426,-1.225848,0.807737,0.646092,-1.030670,-0.066419,-0.505775,0.997204,-0.578736,-0.573809
9996,-1.391939,0.912419,-0.373958,1.724464,-0.306379,-0.911583,0.646092,0.970243,0.027988,-0.505775,0.997204,-0.578736,-0.573809
9997,0.604988,-1.095988,-0.278604,0.687130,-1.225848,-0.911583,-1.547768,0.970243,-1.008643,1.977165,0.997204,-0.578736,-0.573809
9998,1.256835,0.912419,0.293517,-0.695982,-0.022608,0.807737,0.646092,-1.030670,-0.125231,1.977165,-1.002804,1.727904,-0.573809
9999,1.463771,-1.095988,-1.041433,-0.350204,0.859965,-0.911583,0.646092,-1.030670,-1.076370,-0.505775,0.997204,-0.578736,-0.573809

### ANN Implementation

In [66]:
import tensorflow as tf
from tensorflow.keras.models import Sequential # neural network 
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

2026-10-12 20:00:38.742346: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.4.6 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/fireflylaptops/Desktop/My-PC/ml-and-ai-cohort/week05-deep-learning-and-llms/annclassification/ann_venv/lib/python3.11/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/Users/fireflylaptops/Desktop/My-PC/ml-and-ai-cohort/week05-deep-learning-and-llms/annclassification/ann_venv/lib/python3.11/site-packages/traitlets/config/application.py", line 1080, in launch_instance
    app.start()
  File "/Users/fireflylaptops/Desktop/My-PC/ml-and-ai-cohort/week05-deep-learning-and-llms/annclassification/ann_venv/lib/python3.11/site-packages/ipykernel/kernelapp.py", line 768, in start
    self.io_loop.start()
  File "/Users/fireflylaptops/Desktop/My-PC/ml-and-ai-cohort/week05-deep-learning-and-llms/annclassification/ann_venv/lib/python3.11/site-packages/tornado/platform/asyncio.py", line 211, in start
    self.asyncio_loop.run_forever()
  File "/Users/fireflylaptops/.local/share/uv/python/cpython-3.11.14-macos-x86_64-none/lib/python3.11/asyncio/base_events.py", line 608, in run_forever
    self._run_once()
  File "/Users/fireflylaptops/.local/share/uv/python/cpython-3.11.14-macos-x86_64-none/lib/python3.11/asyncio/base_events.py", line 1936, in _run_once
    handle._run()
  File "/Users/fireflylaptops/.local/share/uv/python/cpython-3.11.14-macos-x86_64-none/lib/python3.11/asyncio/events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/fireflylaptops/Desktop/My-PC/ml-and-ai-cohort/week05-deep-learning-and-llms/annclassification/ann_venv/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 678, in shell_main
    await self.dispatch_shell(msg, subshell_id=subshell_id)
  File "/Users/fireflylaptops/Desktop/My-PC/ml-and-ai-cohort/week05-deep-learning-and-llms/annclassification/ann_venv/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 508, in dispatch_shell
    await result
  File "/Users/fireflylaptops/Desktop/My-PC/ml-and-ai-cohort/week05-deep-learning-and-llms/annclassification/ann_venv/lib/python3.11/site-packages/ipykernel/ipkernel.py", line 372, in execute_request
    await super().execute_request(stream, ident, parent)
  File "/Users/fireflylaptops/Desktop/My-PC/ml-and-ai-cohort/week05-deep-learning-and-llms/annclassification/ann_venv/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 891, in execute_request
    reply_content = await reply_content
  File "/Users/fireflylaptops/Desktop/My-PC/ml-and-ai-cohort/week05-deep-learning-and-llms/annclassification/ann_venv/lib/python3.11/site-packages/ipykernel/ipkernel.py", line 460, in do_execute
    res = shell.run_cell(
  File "/Users/fireflylaptops/Desktop/My-PC/ml-and-ai-cohort/week05-deep-learning-and-llms/annclassification/ann_venv/lib/python3.11/site-packages/ipykernel/zmqshell.py", line 686, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/Users/fireflylaptops/Desktop/My-PC/ml-and-ai-cohort/week05-deep-learning-and-llms/annclassification/ann_venv/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3248, in run_cell
    result = self._run_cell(
  File "/Users/fireflylaptops/Desktop/My-PC/ml-and-ai-cohort/week05-deep-learning-and-llms/annclassification/ann_venv/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3305, in _run_cell
    result = runner(coro)
  File "/Users/fireflylaptops/Desktop/My-PC/ml-and-ai-cohort/week05-deep-learning-and-llms/annclassification/ann_venv/lib/python3.11/site-packages/IPython/core/async_helpers.py", line 140, in _pseudo_sync_runner
    coro.send(None)
  File "/Users/fireflylaptops/Desktop/My-PC/ml-and-ai-cohort/week05-deep-learning-and-llms/annclassification/ann_venv/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3518, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/Users/fireflylaptops/Desktop/My-PC/ml-and-ai-cohort/week05-deep-learning-and-llms/annclassification/ann_venv/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3762, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/Users/fireflylaptops/Desktop/My-PC/ml-and-ai-cohort/week05-deep-learning-and-llms/annclassification/ann_venv/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3823, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/ty/9g4bxw293952ssfdsr7zq3j80000gn/T/ipykernel_56922/1349258134.py", line 1, in <module>
    import tensorflow as tf
  File "/Users/fireflylaptops/Desktop/My-PC/ml-and-ai-cohort/week05-deep-learning-and-llms/annclassification/ann_venv/lib/python3.11/site-packages/tensorflow/__init__.py", line 38, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/Users/fireflylaptops/Desktop/My-PC/ml-and-ai-cohort/week05-deep-learning-and-llms/annclassification/ann_venv/lib/python3.11/site-packages/tensorflow/python/__init__.py", line 42, in <module>
    from tensorflow.python.saved_model import saved_model
  File "/Users/fireflylaptops/Desktop/My-PC/ml-and-ai-cohort/week05-deep-learning-and-llms/annclassification/ann_venv/lib/python3.11/site-packages/tensorflow/python/saved_model/saved_model.py", line 20, in <module>
    from tensorflow.python.saved_model import builder
  File "/Users/fireflylaptops/Desktop/My-PC/ml-and-ai-cohort/week05-deep-learning-and-llms/annclassification/ann_venv/lib/python3.11/site-packages/tensorflow/python/saved_model/builder.py", line 23, in <module>
    from tensorflow.python.saved_model.builder_impl import _SavedModelBuilder
  File "/Users/fireflylaptops/Desktop/My-PC/ml-and-ai-cohort/week05-deep-learning-and-llms/annclassification/ann_venv/lib/python3.11/site-packages/tensorflow/python/saved_model/builder_impl.py", line 26, in <module>
    from tensorflow.python.framework import dtypes
  File "/Users/fireflylaptops/Desktop/My-PC/ml-and-ai-cohort/week05-deep-learning-and-llms/annclassification/ann_venv/lib/python3.11/site-packages/tensorflow/python/framework/dtypes.py", line 35, in <module>
    from tensorflow.tsl.python.lib.core import pywrap_ml_dtypes

AttributeError: _ARRAY_API not found

ImportError: numpy.core._multiarray_umath failed to import

ImportError: numpy.core.umath failed to import

TypeError: Unable to convert function return value to a Python type! The signature was
	() -> handle

In [52]:
(X_train.shape[1],)

(12,)

In [54]:
## Build Our ANN Model
model=Sequential([
    Dense(64,activation='relu',input_shape=(X_train.shape[1],)), ## HL1 Connected wwith input layer
    Dense(32,activation='relu'), ## HL2
    Dense(1,activation='sigmoid')  ## output layer
]

)

In [55]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 64)                832

 dense_4 (Dense)             (None, 32)                2080

 dense_5 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [58]:
import tensorflow
opt=tensorflow.keras.optimizers.Adam(learning_rate=0.01)
loss=tensorflow.keras.losses.BinaryCrossentropy()
loss

In [60]:
## compile the model
model.compile(optimizer=opt,loss="binary_crossentropy",metrics=['accuracy'])

In [63]:
## Set up the Tensorboard
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard

log_dir="logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [66]:
## Set up Early Stopping
early_stopping_callback=EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [67]:
### Train the model
history=model.fit(
    X_train,y_train,validation_data=(X_test,y_test),epochs=100,
    callbacks=[tensorflow_callback,early_stopping_callback]
)

Epoch 1/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3496 - accuracy: 0.8591 - val_loss: 0.3424 - val_accuracy: 0.8595
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3426 - accuracy: 0.8622 - val_loss: 0.3427 - val_accuracy: 0.8580
Epoch 3/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3397 - accuracy: 0.8630 - val_loss: 0.3508 - val_accuracy: 0.8605
Epoch 4/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3406 - accuracy: 0.8622 - val_loss: 0.3583 - val_accuracy: 0.8590
Epoch 5/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3378 - accuracy: 0.8626 - val_loss: 0.3424 - val_accuracy: 0.8555
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3322 - accuracy: 0.8654 - val_loss: 0.3423 - val_accuracy: 0.8600
Epoch 7/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3311 - accuracy: 0.8661 - val_loss: 0.3412 - val_accuracy: 0.8605
Epoch 8/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3256 - accuracy: 0.8665 - val_loss: 0.3515 - val_accuracy: 0.8540
Epoch 9/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3280 - accuracy: 0.8665 - val_loss: 0.3623 - val_accuracy: 0.8540
Epoch 10/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3251 - accuracy: 0.8677 - val_loss: 0.3474 - val_accuracy: 0.8540
Epoch 11/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3227 - accuracy: 0.8690 - val_loss: 0.3571 - val_accuracy: 0.8565
Epoch 12/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3216 - accuracy: 0.8664 - val_loss: 0.3565 - val_accuracy: 0.8550
Epoch 13/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3171 - accuracy: 0.8699 - val_loss: 0.3569 - val_accuracy: 0.8570
Epoch 14/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3141 - accuracy: 0.8689 - val_loss: 0.3562 - val_accuracy: 0.8605
Epoch 15/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3141 - accuracy: 0.8704 - val_loss: 0.3554 - val_accuracy: 0.8600
Epoch 16/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3115 - accuracy: 0.8733 - val_loss: 0.3585 - val_accuracy: 0.8555
Epoch 17/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3081 - accuracy: 0.8725 - val_loss: 0.3636 - val_accuracy: 0.8535

In [68]:
model.save('model.h5')

e:\UDemy Final\ANN Classification\venv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [70]:
## Load Tensorboard Extension
%load_ext tensorboard

In [75]:
%tensorboard --logdir logs/fit

Reusing TensorBoard on port 6014 (pid 16084), started 0:00:05 ago. (Use '!kill 16084' to kill it.)

In [ ]:
### Load the pickle file